/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package astba7a;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hazem
 */
public class emploies extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;

    /**
     * Creates new form
     */
    public emploies() {
        initComponents();
        DoConnect();
    }

    public void DoConnect() {
        
        String url = "jdbc:mysql://localhost:3306/";
        String DBname = "astba7a";
        String DBpass = "root";
        String DBuser = "root";
        try {
            //create connection
            con = DriverManager.getConnection(url + DBname, DBuser, DBpass);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        String sql = "select * from emploies";
        try {
            rs = stmt.executeQuery(sql);
            rs.next();
            int i_id = rs.getInt("instructor_id");
            String in_id = Integer.toString(i_id);
            String in_name = rs.getString("instruct_name");
            String ph_num = rs.getString("phone-number");
            String cour_name = rs.getString("course_name");
            String address = rs.getString("address");
            String salary = rs.getString("salary");
            text_instructor_id.setText(in_id);
            text_instrucotr_name.setText(in_name);
            text_phone_number.setText(ph_num);
            text_course_name.setText(cour_name);
            text_addrees.setText(address);
            text_salary.setText(salary);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text_instructor_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_instrucotr_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_phone_number = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_course_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_addrees = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_salary = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        ptnprev = new javax.swing.JButton();
        ptnfirst = new javax.swing.JButton();
        ptnlast = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        stud_id_text = new javax.swing.JTextField();
        student_name_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phone_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lap_text = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cource_txt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("instructor_id");

        jLabel2.setText("instrucotr_name");

        text_instrucotr_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_instrucotr_nameActionPerformed(evt);
            }
        });

        jLabel3.setText("phone_number");

        jLabel5.setText("course_name");

        jLabel6.setText("addrees");

        jLabel4.setText("salary");

        btnnext.setText("next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        ptnprev.setText("previous");
        ptnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnprevActionPerformed(evt);
            }
        });

        ptnfirst.setText("first");
        ptnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnfirstActionPerformed(evt);
            }
        });

        ptnlast.setText("last");
        ptnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnlastActionPerformed(evt);
            }
        });

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("save new record");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("new");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("cancel new record");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_instructor_id)
                            .addComponent(text_instrucotr_name)
                            .addComponent(text_phone_number)
                            .addComponent(text_course_name)
                            .addComponent(text_addrees)
                            .addComponent(text_salary))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ptnprev)
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnnext)
                                        .addGap(60, 60, 60)
                                        .addComponent(ptnfirst)
                                        .addGap(18, 18, 18)
                                        .addComponent(ptnlast))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(text_instructor_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_instrucotr_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_addrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnext)
                    .addComponent(ptnprev)
                    .addComponent(ptnfirst)
                    .addComponent(ptnlast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("enter student id");

        stud_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_id_textActionPerformed(evt);
            }
        });

        jLabel8.setText("name");

        jLabel9.setText("phone");

        jLabel10.setText("lap");

        lap_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lap_textActionPerformed(evt);
            }
        });

        jLabel11.setText("cource");

        jButton6.setText("search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stud_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(student_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(lap_text, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cource_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lap_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cource_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_instrucotr_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_instrucotr_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_instrucotr_nameActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        try {
            if (rs.next()) {
                int i_id = rs.getInt("instructor_id");
                String in_id = Integer.toString(i_id);
                String in_name = rs.getString("instruct_name");
                String ph_num = rs.getString("phone-number");
                String cour_name = rs.getString("course_name");
                String address = rs.getString("address");
                String salary = rs.getString("salary");
                text_instructor_id.setText(in_id);
                text_instrucotr_name.setText(in_name);
                text_phone_number.setText(ph_num);
                text_course_name.setText(cour_name);
                text_addrees.setText(address);
                text_salary.setText(salary);

            } else {
                rs.previous();
                JOptionPane.showMessageDialog(emploies.this, "end of file");
            }
        } catch (SQLException ex) {
            Logger.getLogger(emploies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void ptnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnprevActionPerformed
        try {
            if (rs.previous()) {
                int i_id = rs.getInt("instructor_id");
                String in_id = Integer.toString(i_id);
                String in_name = rs.getString("instruct_name");
                String ph_num = rs.getString("phone-number");
                String cour_name = rs.getString("course_name");
                String address = rs.getString("address");
                String salary = rs.getString("salary");
                text_instructor_id.setText(in_id);
                text_instrucotr_name.setText(in_name);
                text_phone_number.setText(ph_num);
                text_course_name.setText(cour_name);
                text_addrees.setText(address);
                text_salary.setText(salary);

            } else {
                rs.next();
                JOptionPane.showMessageDialog(emploies.this, "end of file");
            }
        } catch (SQLException ex) {
            Logger.getLogger(emploies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ptnprevActionPerformed

    private void ptnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnfirstActionPerformed
        try {
            rs.first();
            int i_id = rs.getInt("instructor_id");
            String in_id = Integer.toString(i_id);
            String in_name = rs.getString("instruct_name");
            String ph_num = rs.getString("phone-number");
            String cour_name = rs.getString("course_name");
            String address = rs.getString("address");
            String salary = rs.getString("salary");
            text_instructor_id.setText(in_id);
            text_instrucotr_name.setText(in_name);
            text_phone_number.setText(ph_num);
            text_course_name.setText(cour_name);
            text_addrees.setText(address);
            text_salary.setText(salary);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(emploies.this, ex.getMessage());
        }
    }//GEN-LAST:event_ptnfirstActionPerformed

    private void ptnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnlastActionPerformed
        try {
            rs.last();
            int i_id = rs.getInt("instructor_id");
            String in_id = Integer.toString(i_id);
            String in_name = rs.getString("instruct_name");
            String ph_num = rs.getString("phone-number");
            String cour_name = rs.getString("course_name");
            String address = rs.getString("address");
            String salary = rs.getString("salary");
            text_instructor_id.setText(in_id);
            text_instrucotr_name.setText(in_name);
            text_phone_number.setText(ph_num);
            text_course_name.setText(cour_name);
            text_addrees.setText(address);
            text_salary.setText(salary);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(emploies.this, ex.getMessage());
        }
    }//GEN-LAST:event_ptnlastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String i_id = text_instructor_id.getText();
        String in_name = text_instrucotr_name.getText();
        String ph_num = text_phone_number.getText();
        String cour_name = text_course_name.getText();
        String address = text_addrees.getText();
        String salary = text_salary.getText();
        int new_i_id = Integer.parseInt(i_id);
        try {
           
            rs.updateInt("instructor_id", new_i_id);
            rs.updateString("instruct_name", in_name);
            rs.updateString("phone-number", ph_num);
            rs.updateString("course_name", cour_name);
            rs.updateString("address", address);
            rs.updateString("salary", salary);
              rs.updateRow();
           
            JOptionPane.showMessageDialog(emploies.this, "updated");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            curRow = rs.getRow();
            text_instructor_id.setText("");
            text_instrucotr_name.setText("");
            text_phone_number.setText("");
            text_course_name.setText("");
            text_addrees.setText("");
            text_salary.setText("");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        ptnprev.setEnabled(false);
        btnnext.setEnabled(false);
        ptnfirst.setEnabled(false);
        ptnlast.setEnabled(false);
        jButton1.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton2.setEnabled(true);
        jButton5.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            rs.absolute(curRow);
            text_instructor_id.setText(Integer.toString(rs.getInt("instructor_id")));
            text_instrucotr_name.setText(rs.getString("instruct_name"));
            text_phone_number.setText(rs.getString("phone-number"));
            text_course_name.setText(rs.getString("course_name"));
            text_addrees.setText(rs.getString("address"));
            text_salary.setText(rs.getString("salary"));

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        ptnprev.setEnabled(true);
        btnnext.setEnabled(true);
        ptnfirst.setEnabled(true);
        ptnlast.setEnabled(true);
        jButton1.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton2.setEnabled(false);
        jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String i_id = text_instructor_id.getText();
        String in_name = text_instrucotr_name.getText();
        String ph_num = text_phone_number.getText();
        String cour_name = text_course_name.getText();
        String address = text_addrees.getText();
        String salary = text_salary.getText();
        int new_i_id = Integer.parseInt(i_id);
        try {
            rs.moveToInsertRow();
            rs.updateInt("instructor_id", new_i_id);
            rs.updateString("instruct_name", in_name);
            rs.updateString("phone-number", ph_num);
            rs.updateString("course_name", cour_name);
            rs.updateString("address", address);
            rs.updateString("salary", salary);
            rs.insertRow();
            stmt.close();
            con.close();
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "select * from emploies";
            rs = stmt.executeQuery(sql);
            rs.next();
            int i_idi = rs.getInt("instructor_id");
            String in_idi = Integer.toString(i_idi);
            String ins_name = rs.getString("instruct_name");
            String pho_num = rs.getString("phone-number");
            String cours_name = rs.getString("course_name");
            String addres_s = rs.getString("address");
            String salar_y = rs.getString("salary");
            text_instructor_id.setText(in_idi);
            text_instrucotr_name.setText(ins_name);
            text_phone_number.setText(pho_num);
            text_course_name.setText(cours_name);
            text_addrees.setText(addres_s);
            text_salary.setText(salar_y);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            rs.deleteRow();
           
            String sql = "select * from emploies";
            rs = stmt.executeQuery(sql);
            rs.next();
            int i_idi = rs.getInt("instructor_id");
            String in_idi = Integer.toString(i_idi);
            String ins_name = rs.getString("instruct_name");
            String pho_num = rs.getString("phone-number");
            String cours_name = rs.getString("course_name");
            String addres_s = rs.getString("address");
            String salar_y = rs.getString("salary");
            text_instructor_id.setText(in_idi);
            text_instrucotr_name.setText(ins_name);
            text_phone_number.setText(pho_num);
            text_course_name.setText(cours_name);
            text_addrees.setText(addres_s);
            text_salary.setText(salar_y);
            
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(emploies.this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stud_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stud_id_textActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        String id_sudent=stud_id_text.toString();
        int x =Integer.parseInt(id_sudent);
        
        try {
           
            
            PreparedStatement st = con.prepareStatement("select * from students where student_id=?");
            st.setInt(1, x);
            ResultSet rss=st.executeQuery();

            if(rss.next()){

            String s1=rss.getString("student_name");
            int s2=rss.getInt("phone_number");
            String ss2=Integer.toString(s2);
            int s3 =rss.getInt("lap_num");
            String ss3=Integer.toString(s3);
            String s4=rss.getString("course_name");
            
            
            
            student_name_text.setText(s1);
            phone_text.setText(ss2);
            lap_text.setText(ss3);
            cource_txt.setText(s4);
            
            
            }else{
                JOptionPane.showMessageDialog(null, "id not found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(emploies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void lap_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lap_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emploies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emploies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emploies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emploies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emploies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JTextField cource_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lap_text;
    private javax.swing.JTextField phone_text;
    private javax.swing.JButton ptnfirst;
    private javax.swing.JButton ptnlast;
    private javax.swing.JButton ptnprev;
    private javax.swing.JTextField stud_id_text;
    private javax.swing.JTextField student_name_text;
    private javax.swing.JTextField text_addrees;
    private javax.swing.JTextField text_course_name;
    private javax.swing.JTextField text_instrucotr_name;
    private javax.swing.JTextField text_instructor_id;
    private javax.swing.JTextField text_phone_number;
    private javax.swing.JTextField text_salary;
    // End of variables declaration//GEN-END:variables
}
